name: ace0
channels:
  - pytorch
  - nvidia
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - alsa-lib=1.2.3.2=h166bdaf_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - blas=1.0=mkl
  - blosc=1.21.3=h6a678d5_0
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - brotlipy=0.7.0=py38h27cfd23_1003
  - brunsli=0.1=h2531618_0
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.19.0=h5eee18b_0
  - ca-certificates=2024.7.2=h06a4308_0
  - cairo=1.16.0=h6cf1ce9_1008
  - certifi=2024.7.4=py38h06a4308_0
  - cffi=1.15.1=py38h5eee18b_3
  - cfitsio=3.470=h5893167_7
  - charls=2.2.0=h2531618_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cloudpickle=2.0.0=pyhd3eb1b0_0
  - contourpy=1.0.5=py38hdb19cb5_0
  - cryptography=39.0.1=py38h9ce1e76_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cycler=0.11.0=pyhd8ed1ab_0
  - cytoolz=0.12.0=py38h5eee18b_0
  - dask-core=2022.7.0=py38h06a4308_0
  - dataclasses=0.8=pyhc8e2a94_3
  - dbus=1.13.6=h48d8840_2
  - expat=2.4.8=h27087fc_0
  - ffmpeg=4.3.2=hca11adc_0
  - filelock=3.9.0=py38h06a4308_0
  - flit-core=3.8.0=py38h06a4308_0
  - fontconfig=2.14.0=h8e229c2_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - freetype-py=2.3.0=pyhd8ed1ab_0
  - fsspec=2023.3.0=py38h06a4308_0
  - future=0.18.3=pyhd8ed1ab_0
  - gettext=0.19.8.1=h73d1719_1008
  - giflib=5.2.1=h5eee18b_3
  - glib=2.68.4=h9c3ff4c_1
  - glib-tools=2.68.4=h9c3ff4c_1
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py38heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - graphite2=1.3.13=h58526e2_1001
  - gst-plugins-base=1.18.5=hf529b03_0
  - gstreamer=1.18.5=h76c114f_0
  - harfbuzz=2.9.1=h83ec7ef_1
  - hdf5=1.10.6=nompi_h6a2412b_1114
  - icu=68.2=h9c3ff4c_0
  - idna=3.4=py38h06a4308_0
  - imagecodecs-lite=2019.12.3=py38h71d37f0_5
  - imageio=2.26.0=py38h06a4308_0
  - importlib_resources=5.12.0=pyhd8ed1ab_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jasper=1.900.1=h07fcdf6_1006
  - jinja2=3.1.2=py38h06a4308_0
  - joblib=1.1.1=py38h06a4308_0
  - jpeg=9e=h5eee18b_1
  - jxrlib=1.1=h7b6447c_2
  - kiwisolver=1.4.4=py38h6a678d5_0
  - krb5=1.19.4=h568e23c_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libaec=1.0.4=he6710b0_1
  - libblas=3.9.0=12_linux64_mkl
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libcblas=3.9.0=12_linux64_mkl
  - libclang=11.1.0=default_ha53f305_1
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.6.0.25=0
  - libcurand=10.3.2.56=0
  - libcurl=7.88.1=h91b91d3_0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.17=h5eee18b_0
  - libedit=3.1.20221030=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.10=h9b69904_4
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.68.4=h174f98d_1
  - libglu=9.0.0=hf484d3e_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - liblapack=3.9.0=12_linux64_mkl
  - liblapacke=3.9.0=12_linux64_mkl
  - libllvm11=11.1.0=hf817b99_2
  - libnghttp2=1.46.0=hce63b2e_0
  - libnpp=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libogg=1.3.4=h7f98852_1
  - libopencv=4.4.0=py38_2
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.39=h5eee18b_0
  - libpq=13.3=hd57d9b9_0
  - libssh2=1.10.0=h8f2d780_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=hf544144_3
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=2.32.1=h7f98852_1000
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - libxcb=1.13=h7f98852_1004
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.12=h72842e0_0
  - libzopfli=1.0.3=he6710b0_0
  - locket=1.0.0=py38h06a4308_0
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.1=py38h7f8727e_0
  - matplotlib=3.7.1=py38h578d9bd_0
  - matplotlib-base=3.7.1=py38h417a72b_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.2.1=py38h06a4308_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=8.0.25=ha770c72_2
  - mysql-libs=8.0.25=hfa10184_2
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=2.8.4=py38h06a4308_1
  - nspr=4.32=h9c3ff4c_1
  - nss=3.69=hb5efdd6_1
  - numpy=1.23.5=py38h14f4228_0
  - numpy-base=1.23.5=py38h31eccc5_0
  - opencv=4.4.0=py38_2
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=1.1.1w=h7f8727e_0
  - packaging=23.0=py38h06a4308_0
  - partd=1.2.0=pyhd3eb1b0_1
  - pcre=8.45=h9c3ff4c_0
  - pillow=9.4.0=py38h6a678d5_0
  - pip=23.0.1=py38h06a4308_0
  - pixman=0.40.0=h36c2ea0_0
  - pooch=1.4.0=pyhd3eb1b0_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - py-opencv=4.4.0=py38h23f93f0_2
  - pycparser=2.21=pyhd3eb1b0_0
  - pyglet=1.5.27=py38h578d9bd_3
  - pyopengl=3.1.6=pyhd8ed1ab_1
  - pyopenssl=23.0.0=py38h06a4308_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyqt=5.12.3=py38ha8c2ead_4
  - pyrender=0.1.45=pyh8a188c0_3
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.16=h7a1cb2a_3
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytorch=2.0.0=py3.8_cuda11.8_cudnn8.7.0_0
  - pytorch-cuda=11.8=h7e8668a_3
  - pytorch-mutex=1.0=cuda
  - pywavelets=1.4.1=py38h5eee18b_0
  - pyyaml=6.0=py38h5eee18b_1
  - qt=5.12.9=hda022c4_4
  - readline=8.2=h5eee18b_0
  - requests=2.28.1=py38h06a4308_1
  - scikit-image=0.19.3=py38h6a678d5_1
  - scipy=1.10.0=py38h14f4228_1
  - setuptools=65.6.3=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.9=h295c915_0
  - sqlite=3.41.1=h5eee18b_0
  - sympy=1.11.1=py38h06a4308_0
  - tifffile=2020.6.3=py_0
  - tk=8.6.12=h1ccaba5_0
  - toolz=0.12.0=py38h06a4308_0
  - torchaudio=2.0.0=py38_cu118
  - torchtriton=2.0.0=py38
  - torchvision=0.15.0=py38_cu118
  - tornado=6.1=py38h0a891b7_3
  - trimesh=3.21.2=pyhd8ed1ab_0
  - typing_extensions=4.4.0=py38h06a4308_0
  - urllib3=1.26.14=py38h06a4308_0
  - wheel=0.38.4=py38h06a4308_0
  - x264=1!161.3030=h7f98852_1
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.10=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zfp=0.5.5=h295c915_6
  - zipp=3.15.0=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.2=ha4553b6_0
  - pip:
      - pyqt5-sip==4.19.18
      - pyqtchart==5.12
      - pyqtwebengine==5.12.1
      - roma==1.4.1
      - timm==0.6.7
      - pycolmap==0.4.0